// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwzdrudtrbbenftvhgza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3emRydWR0cmJiZW5mdHZoZ3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDUwNTUsImV4cCI6MjA3NDEyMTA1NX0.ywktpnfPD01wTRx9VPNFqd614Q3hVE_GVCwSludgVLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});